name: Setup Server Blockmango Remake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up h
      run: |
        # Download and extract ngrok
        Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath "C:\ngrok"
        Remove-Item ngrok.zip
        # Configure ngrok using authtoken from secrets
        C:\ngrok\ngrok.exe authtoken "${{ secrets.NGROK_AUTH }}"

    - name: Install h
      run: |
        # Download and install TightVNC Server
        Invoke-WebRequest -Uri https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-gpl-setup-64bit.msi -OutFile tightvnc.msi
        Start-Process msiexec.exe -ArgumentList '/i tightvnc.msi /quiet /norestart' -Wait
        Remove-Item tightvnc.msi

    - name: Configure h Password
      run: |
        # Set TightVNC passwords (replace 'adminpassword' and 'viewonlypassword' with secrets)
        $password = "${{ secrets.VNC_PASSWORD }}"
        $viewPassword = "${{ secrets.VNC_VIEWONLY_PASSWORD }}"

        # Configure passwords
        reg add "HKLM\SOFTWARE\TightVNC\Server" /v Password /t REG_BINARY /d $(echo -n $password | openssl md5 -binary | Format-Hex -AsByteString) /f
        reg add "HKLM\SOFTWARE\TightVNC\Server" /v PasswordViewOnly /t REG_BINARY /d $(echo -n $viewPassword | openssl md5 -binary | Format-Hex -AsByteString) /f

        # Allow full control
        reg add "HKLM\SOFTWARE\TightVNC\Server" /v RfbPort /t REG_DWORD /d 5900 /f

    - name: Allow h through Firewall
      run: |
        # Allow TightVNC through Windows Firewall on port 5900
        New-NetFirewallRule -DisplayName "Allow VNC" -Direction Inbound -Protocol TCP -Action Allow -LocalPort 5900

    - name: Start h Server
      run: |
        # Start TightVNC Server
        Start-Process -NoNewWindow -FilePath "C:\Program Files\TightVNC\tvnserver.exe"

    - name: Start n TCP Tunnel for h
      run: |
        # Start ngrok TCP tunnel on port 5900
        Start-Process -NoNewWindow -FilePath "C:\ngrok\ngrok.exe" -ArgumentList "tcp 5900"

    - name: Keep session alive
      run: |
        # Keep the session alive with periodic checks
        while ($true) {
          Write-Output "VNC session is alive."
          Start-Sleep -Seconds 60
        }
